import {bangkokDay,readAll,lockFinanceForm} from './finance-core.js?v=20261007-analysis15';
import {rentCategories,rentAmounts,duplicateRentMonth,availableRentPayments} from './rent-core.js?v=20261007-analysis15';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const db=createClient('https://mmvdhopogchcxwlstflk.supabase.co','sb_publishable_PYkDjHN3ULlFW9BavMvAVQ_d77eZZ5W');
const $=id=>document.getElementById(id),money=n=>document.body.classList.contains('privacy-mode')?'฿ ••••':new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(n||0)),month=s=>new Date(s.slice(0,7)+'-01T00:00:00').toLocaleDateString('th-TH',{month:'long',year:'numeric'}),day=s=>s?new Date(s+'T00:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}):'—';
let user,rows=[],transactions=[],accounts=[],categories=[],editing=null,autoHalf=true;
function option(el,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;el.append(o);}
function message(s,saved=false){$('rentMessage').dataset.loading='false';$('rentMessage').textContent=s;$('rentSavedLink').hidden=!saved;}
async function load(){[rows,transactions]=await Promise.all([
 readAll(()=>db.from('rent_records').select('*').eq('user_id',user.id).order('bill_month',{ascending:false}).order('id')),
 readAll(()=>db.from('transactions').select('*,categories(name)').eq('user_id',user.id).eq('type','expense').order('transaction_date',{ascending:false}).order('id'))
]);render();}
function render(){const root=$('rentHistory');root.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='muted';p.textContent='ยังไม่มีบิลค่าห้องเช่า เริ่มเพิ่มบิลด้านบนได้เลย';root.append(p);}
 for(const r of rows){const card=document.createElement('article');card.className='rent-bill';const title=document.createElement('h3');title.textContent=month(r.bill_month);const detail=document.createElement('p');detail.textContent='บิลเต็ม '+money(r.full_amount)+' · ส่วนมิว '+money(r.my_amount);const paid=document.createElement('p');paid.className='muted';paid.textContent=r.status==='paid'?'จ่ายจริง '+day(r.payment_date):'ยังไม่จ่าย · ยังไม่ลงรายจ่าย';const note=document.createElement('p');note.textContent=r.note||'';const edit=document.createElement('button');edit.type='button';edit.className='btn small soft';edit.textContent='ดู / แก้ไข';edit.onclick=()=>{if($('saveRent').disabled)return;open(r);$('rentForm').scrollIntoView({behavior:'smooth',block:'start'});};card.append(title,detail,paid,note,edit);root.append(card);}
}
function open(r=null){editing=r;autoHalf=!r;$('rentForm').reset();$('rentError').textContent='';$('rentTitle').textContent=r?'แก้ไขค่าห้องเช่า':'เพิ่มค่าห้องเช่า';$('rentMonth').value=r?.bill_month.slice(0,7)||bangkokDay().slice(0,7);$('rentStatus').value=r?.status||'paid';$('rentDate').value=r?.payment_date||bangkokDay();$('rentFull').value=r?.full_amount??'';$('rentMy').value=r?.my_amount??'';$('rentNote').value=r?.note||'';
 $('rentAccount').replaceChildren();option($('rentAccount'),'','ไม่ระบุบัญชี');accounts.forEach(a=>option($('rentAccount'),a.id,a.name));$('rentAccount').value=r?.account_id||'';
 $('rentCategory').replaceChildren();categories.forEach(c=>option($('rentCategory'),c.id,c.name));$('rentCategory').value=r?.category_id||categories.find(c=>c.name==='ห้องเช่า')?.id||categories[0]?.id||'';
 $('rentExisting').replaceChildren();option($('rentExisting'),'','ยังไม่ได้ลง — สร้างรายการจ่ายครั้งเดียว');availableRentPayments(transactions,rows).forEach(t=>option($('rentExisting'),t.id,day(t.transaction_date)+' · '+money(t.amount)+' · '+t.description));if(r?.transaction_id){option($('rentExisting'),r.transaction_id,'เชื่อมรายการจ่ายเดิมแล้ว');$('rentExisting').value=r.transaction_id;}sync();}
function half(){if($('rentFull').value!=='')$('rentMy').value=(Math.round(Math.round(Number($('rentFull').value)*100)/2)/100).toFixed(2);}
function sync(){const paid=$('rentStatus').value==='paid';$('rentDate').required=paid;$('rentDate').disabled=!paid;$('rentExisting').disabled=!paid||!!editing?.transaction_id;preview();}
function preview(){const duplicate=duplicateRentMonth(rows,$('rentMonth').value,editing?.id);$('rentPreview').textContent=duplicate?'มีบิลเดือนนี้แล้ว กรุณาแก้ไขจากประวัติด้านล่าง':$('rentMonth').value?'ค่าห้องของ '+month($('rentMonth').value)+' · '+($('rentStatus').value==='paid'?'ลงรายจ่ายเต็มในวันที่ '+day($('rentDate').value):'เก็บบิลไว้ ยังไม่ลงรายจ่าย'):'';}
$('newRent').onclick=()=>{if(!$('saveRent').disabled)open();};$('rentFull').oninput=()=>{if(autoHalf)half();preview();};$('rentMy').oninput=()=>{autoHalf=false;};$('rentHalf').onclick=()=>{autoHalf=true;half();};$('rentStatus').onchange=sync;$('rentMonth').onchange=$('rentDate').onchange=preview;
$('rentExisting').onchange=()=>{const t=transactions.find(x=>x.id===$('rentExisting').value);if(!t)return;$('rentFull').value=t.amount;half();autoHalf=true;$('rentDate').value=t.transaction_date;$('rentAccount').value=t.account_id||'';$('rentCategory').value=t.category_id;$('rentNote').value=t.note||'';preview();};
$('rentForm').onsubmit=async e=>{e.preventDefault();const b=$('saveRent');if(b.disabled)return;$('rentError').textContent='';let committed=false;const unlock=lockFinanceForm($('rentForm'));b.disabled=true;
 try{if(duplicateRentMonth(rows,$('rentMonth').value,editing?.id))throw new Error('เดือนนี้มีบิลแล้ว กรุณาแก้ไขรายการเดิม');const amounts=rentAmounts($('rentFull').value,$('rentMy').value);const row={user_id:user.id,bill_month:$('rentMonth').value+'-01',payment_date:$('rentStatus').value==='paid'?$('rentDate').value:null,status:$('rentStatus').value,...amounts,account_id:$('rentAccount').value||null,category_id:$('rentCategory').value,note:$('rentNote').value.trim()||null};
 if(!row.category_id)throw new Error('เพิ่มหมวดค่าห้องเช่าที่หน้าหมวดหมู่ก่อน');if(!editing?.transaction_id&&row.status==='paid'&&$('rentExisting').value)row.transaction_id=$('rentExisting').value;
 const q=editing?db.from('rent_records').update(row).eq('id',editing.id).eq('user_id',user.id):db.from('rent_records').insert(row);const result=await q.select('id').single();if(result.error)throw result.error;committed=true;await load();open(rows.find(r=>r.id===result.data.id)||null);message(row.status==='paid'?'บันทึกแล้ว ✓ รายจ่ายเต็มเชื่อมครั้งเดียว ส่วนมิวแสดงตามที่กรอก':'เก็บบิลแล้ว ✓ ยังไม่ลงรายจ่าย',row.status==='paid');
 }catch(err){if(committed){$('rentApp').classList.add('hidden');message('บันทึกสำเร็จแล้ว แต่โหลดข้อมูลล่าสุดไม่ได้ กรุณารีเฟรชก่อนทำรายการต่อ');}else $('rentError').textContent=err.code==='23505'?'เดือนนี้มีบิลแล้ว กรุณารีเฟรชและแก้ไขรายการเดิม':err.message;}finally{unlock();b.disabled=false;sync();}
};
try{const u=await db.auth.getUser();if(u.error||!u.data.user)message('กรุณาเข้าสู่ระบบที่หน้าหลัก แล้วกลับมาหน้าค่าห้องเช่า');else{user=u.data.user;[accounts,categories]=await Promise.all([readAll(()=>db.from('accounts').select('id,name').eq('user_id',user.id).order('name').order('id')),readAll(()=>db.from('categories').select('id,name').eq('user_id',user.id).eq('type','expense').order('name').order('id'))]);categories=categories.filter(c=>rentCategories.includes(c.name));await load();open();$('rentApp').classList.remove('hidden');message('พร้อมบันทึกค่าห้องเช่า');}}catch(err){message('โหลดไม่ได้: '+err.message);}
