import {bangkokDay,readAll,lockFinanceForm} from './finance-core.js?v=20261006-logout1';
import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const supabase=createClient('https://mmvdhopogchcxwlstflk.supabase.co','sb_publishable_PYkDjHN3ULlFW9BavMvAVQ_d77eZZ5W');
const $=id=>document.getElementById(id),money=n=>document.body?.classList.contains('privacy-mode')?'฿ ••••':new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(n);
const earnings=[['base_salary','เงินเดือนพื้นฐาน'],['overtime','OT'],['allowance','เบี้ยเลี้ยง / ค่าตำแหน่ง'],['bonus','โบนัส'],['other_income','รายได้อื่น']];
const deductions=[['social_security','ประกันสังคม'],['tax','ภาษีหัก ณ ที่จ่าย'],['provident_fund','กองทุนสำรองเลี้ยงชีพ'],['other_deductions','รายการหักอื่น']];
const fields=[...earnings,...deductions]; let user,records=[],incomes=[],editing=null;
function message(s){$('salaryMessage').textContent=s;}
const today=bangkokDay;let defaultSalaryCategory='';
function cents(id){return Math.round(Number($(id).value||0)*100);}
function totals(){const gross=earnings.reduce((s,[id])=>s+cents(id),0),deduct=deductions.reduce((s,[id])=>s+cents(id),0);$('netSalary').textContent=money((gross-deduct)/100);$('salaryTotals').textContent='รายได้รวม '+money(gross/100)+' · หักรวม '+money(deduct/100);return (gross-deduct)/100;}
function option(select,value,label){const el=document.createElement('option');el.value=value;el.textContent=label;select.append(el);}
function reset(){editing=null;$('salaryForm').reset();$('category_id').value=defaultSalaryCategory;$('salary_month').value=today().slice(0,7);$('salary_month').disabled=false;$('payment_date').value=today();fields.forEach(([id])=>$(id).value='0');$('saveSalary').textContent='บันทึกเงินเดือน';linkOptions();totals();}
function linkOptions(){const s=$('transaction_id');s.replaceChildren();option(s,'','สร้างรายรับใหม่อัตโนมัติ');const linked=new Set(records.map(r=>r.transaction_id));for(const t of incomes.filter(t=>!linked.has(t.id)||records.find(r=>r.id===editing)?.transaction_id===t.id)){option(s,t.id,t.transaction_date+' · '+t.description+' · '+money(t.amount));}s.disabled=!!editing;}
async function load(){
 const [r,c,a,t]=await Promise.all([
  readAll(()=>supabase.from('salary_records').select('*').eq('user_id',user.id).order('salary_month',{ascending:false}).order('id')),
  readAll(()=>supabase.from('categories').select('id,name').eq('user_id',user.id).eq('type','income').order('name').order('id')),
  readAll(()=>supabase.from('accounts').select('id,name').eq('user_id',user.id).order('name').order('id')),
  readAll(()=>supabase.from('transactions').select('id,transaction_date,description,amount').eq('user_id',user.id).eq('type','income').neq('status','cancelled').order('transaction_date',{ascending:false}).order('id'))
 ]);
 records=r;incomes=t;
 for(const [id,data] of [['category_id',c],['account_id',a]]){const s=$(id);s.replaceChildren();option(s,'','เลือก'+(id==='account_id'?'บัญชี':'หมวด'));data.forEach(x=>option(s,x.id,x.name))}
 defaultSalaryCategory=c.find(x=>/เงินเดือน/.test(x.name))?.id||'';
 $('category_id').value=defaultSalaryCategory;renderHistory();linkOptions();
}
function renderHistory(){const root=$('salaryHistory');root.replaceChildren();if(!records.length){const p=document.createElement('p');p.className='empty';p.textContent='ยังไม่มีรายละเอียดเงินเดือน เริ่มบันทึกเดือนแรกได้เลย';root.append(p);return;}for(const r of records){const card=document.createElement('div');card.className='card';const row=document.createElement('div');row.className='row';const text=document.createElement('div');const title=document.createElement('b');title.textContent='เงินเดือน '+r.salary_month.slice(0,7)+' · '+money(r.net_amount);const info=document.createElement('div');info.className='muted';info.textContent='เงินเข้า '+r.payment_date+' · รายรับสุทธิเชื่อมแล้ว';text.append(title,info);const btn=document.createElement('button');btn.type='button';btn.className='btn small soft';btn.textContent='ดู / แก้ไข';btn.onclick=()=>edit(r);row.append(text,btn);card.append(row);root.append(card);}}
function edit(r){if($('saveSalary').disabled)return;editing=r.id;$('salary_month').value=r.salary_month.slice(0,7);$('salary_month').disabled=true;$('payment_date').value=r.payment_date;$('account_id').value=r.account_id;$('category_id').value=r.category_id;fields.forEach(([id])=>$(id).value=r[id]);$('salary_note').value=r.note||'';linkOptions();$('transaction_id').value=r.transaction_id;$('saveSalary').textContent='บันทึกการแก้ไข';totals();$('salaryForm').scrollIntoView({behavior:'smooth'});}
for(const [root,list] of [['earningFields',earnings],['deductionFields',deductions]])for(const [id,label] of list){const div=document.createElement('div');div.className='field';const l=document.createElement('label');l.htmlFor=id;l.textContent=label;const input=document.createElement('input');input.id=id;input.type='number';input.min='0';input.max='999999999999.99';input.step='0.01';input.value='0';input.required=true;input.addEventListener('input',totals);div.append(l,input);$(root).append(div);}
$('newSalary').onclick=()=>{if($('saveSalary').disabled)return;reset();message('เริ่มบันทึกเดือนใหม่');};
$('salaryForm').onsubmit=async e=>{e.preventDefault();if($('saveSalary').disabled)return;if(!Number.isFinite(totals())||totals()<=0)return message('ยอดรับสุทธิต้องมากกว่า 0 บาท');const month=$('salary_month').value+'-01';if(!editing&&records.some(r=>r.salary_month===month))return message('เดือนนี้บันทึกแล้ว กดดู / แก้ไขรายการเดิมได้เลย');const row={user_id:user.id,salary_month:month,payment_date:$('payment_date').value,account_id:$('account_id').value,category_id:$('category_id').value,transaction_id:editing?records.find(r=>r.id===editing).transaction_id:($('transaction_id').value||null),note:$('salary_note').value.trim()||null};fields.forEach(([id])=>row[id]=cents(id)/100);const btn=$('saveSalary'),unlock=lockFinanceForm($('salaryForm'));btn.disabled=true;let committed=false;try{const q=editing?supabase.from('salary_records').update(row).eq('id',editing).eq('user_id',user.id):supabase.from('salary_records').insert(row);const {data,error}=await q.select('id').single();if(error)throw error;if(!data)throw new Error('ไม่พบรายการที่บันทึก');committed=true;await load();reset();message('บันทึกแล้ว ✅ รายรับสุทธิอัปเดตในภาพรวมแล้ว');}catch(error){if(committed){$('salaryApp').classList.add('hidden');message('บันทึกสำเร็จแล้ว แต่โหลดข้อมูลล่าสุดไม่ได้ กรุณารีเฟรชก่อนทำรายการต่อ');return;}message(error.code==='23505'?'เดือนนี้หรือรายรับนี้เชื่อมไว้แล้ว กรุณาเปิดรายการเดิม':'บันทึกไม่ได้: '+error.message);}finally{unlock();btn.disabled=false;if(!editing)$('salary_month').disabled=false;linkOptions();}};
$('exportSalary').onclick=()=>{if(!records.length)return message('ยังไม่มีเงินเดือนให้ส่งออก');if(!window.XLSX)return message('โหลดเครื่องมือ Excel ไม่สำเร็จ กรุณารีเฟรชแล้วลองใหม่');const data=records.map(r=>{const out={'เดือนเงินเดือน':r.salary_month.slice(0,7),'วันที่รับเงิน':r.payment_date};fields.forEach(([id,label])=>out[label]=Number(r[id]));out['รับสุทธิ']=Number(r.net_amount);out['หมายเหตุ']=r.note||'';return out;});const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(data);ws['!cols']=Object.keys(data[0]).map(()=>({wch:22}));XLSX.utils.book_append_sheet(wb,ws,'เงินเดือน');XLSX.writeFile(wb,'My_Finance_Salary.xlsx');};
try{const {data,error}=await supabase.auth.getUser();if(error||!data.user){message('กรุณาเข้าสู่ระบบที่หน้าหลัก แล้วกลับมาหน้าเงินเดือน');}else{user=data.user;await load();reset();$('salaryApp').classList.remove('hidden');message('ยอดสุทธิเท่านั้นที่นับเป็นรายรับ · '+user.email);}}catch(e){message('โหลดข้อมูลไม่ได้: '+e.message);}


