import assert from 'node:assert/strict';
import {financialBackupTables,financeExcelSheets,createFinanceWorkbook} from '../finance-backup.js';
const backup={format:'my-finance-backup',version:1,owner_id:'owner',exported_at:'2026-10-08T05:00:00Z',data:Object.fromEntries(financialBackupTables.map(k=>[k,[]]))};
backup.data.transactions=[{id:'a',user_id:'owner',type:'income',amount:'100.10',transaction_date:'2026-09-01',status:'paid',note:'=SUM(A1:A2)'},{id:'b',user_id:'owner',type:'expense',amount:'20.05',transaction_date:'2026-09-02',status:'paid'},{id:'c',user_id:'owner',type:'expense',amount:'99',transaction_date:'2026-09-03',status:'cancelled'},{id:'d',user_id:'owner',type:'expense',amount:'30',transaction_date:'2026-10-01',status:'paid'}];
backup.data.accounts=[{id:'bank',user_id:'owner',account_number:'0012345678',opening_balance:'42.50'}];
backup.data.rent_records=[{id:'rent',user_id:'owner',bill_month:'2026-08-01',payment_date:'2026-09-05',full_amount:'1000',my_amount:'500'},{id:'pending',user_id:'owner',bill_month:'2026-09-01',payment_date:null}];
const sheets=financeExcelSheets(backup,{from:'2026-09-01',to:'2026-09-30'});
assert.equal(sheets.length,12);assert.deepEqual(sheets[0].rows[1],['2026-09',100.1,20.05,80.05,2]);
assert.equal(sheets.find(s=>s.name==='รายการ').rows.length,4,'cancelled rows retained in detail');
assert.equal(sheets.find(s=>s.name==='ค่าห้องเช่า').rows.length,2,'filter by payment date rather than bill month');
assert.equal(financeExcelSheets(backup).find(s=>s.name==='ค่าห้องเช่า').rows.length,3,'all export includes unpaid records');
assert.throws(()=>financeExcelSheets(backup,{from:'2026-02-30'}));assert.throws(()=>financeExcelSheets(backup,{from:'2026-10-01',to:'2026-09-01'}));
let book;
const XLSX={utils:{book_new:()=>book={sheets:[]},encode_cell:({r,c})=>r+':'+c,aoa_to_sheet:rows=>{const s={'!ref':'A1:Z10'};rows.forEach((row,r)=>row.forEach((v,c)=>s[r+':'+c]={v,t:typeof v==='number'?'n':'s'}));return s;},book_append_sheet:(b,s,name)=>b.sheets.push({name,s})}};
createFinanceWorkbook(XLSX,backup,{});
const account=book.sheets.find(s=>s.name==='บัญชี').s;
assert(Object.values(account).some(c=>c?.v==='0012345678'&&c.t==='s'),'account leading zeros stay text');
const tx=book.sheets.find(s=>s.name==='รายการ').s;
assert(Object.values(tx).some(c=>c?.v==='=SUM(A1:A2)'&&c.t==='s'&&!c.f),'user text never becomes formula');
assert(Object.values(tx).some(c=>c?.z==='dd/mm/yyyy'&&c.t==='n'),'dates typed and formatted');
backup.data.transactions[0].user_id='another';assert.throws(()=>financeExcelSheets(backup));
console.log('PASS Excel: owner validation, selected periods, cancelled detail, payment dates, cent totals, typed amounts/dates, identifier zeros and text safety');
